library(readr)
HR_comma_sep <- read_csv("C:/Users/danie/Desktop/HUMAN RESOURCES ANALYTICS - EQUIPO ANALISIS DE DATOS/HR_comma_sep.csv")
View(HR_comma_sep)
library(MultBiplotR)
attach(HR_comma_sep)
typeof(salary)
HR_comma_sep$salary <- as.factor(HR_comma_sep$salary)
typeof(HR_comma_sep$salary)
typeof(sales)
HR_comma_sep$sales <- as.factor(HR_comma_sep$sales)
typeof(HR_comma_sep$sales)
library(dplyr)
Manovabiplot_dataset <- select(HR_comma_sep, -Work_accident, -left, -promotion_last_5years, -sales)
Manova_biplot <- CanonicalBiplot(Manovabiplot_dataset[,1:5], Manovabiplot_dataset$salary, MANOVA = TRUE)
summary(Manova_biplot)
plot(Manova_biplot, LabelInd = FALSE)
library(dplyr)
Manovabiplot_dataset <- select(HR_comma_sep, -Work_accident, -left, -promotion_last_5years, -salary)
Manova_biplot <- CanonicalBiplot(Manovabiplot_dataset[,1:5], Manovabiplot_dataset$sales, MANOVA = TRUE)
summary(Manova_biplot)
plot(Manova_biplot, LabelInd = FALSE)
HJ_biplot <- HJ.Biplot(Manovabiplot_dataset[,1:5], dimension = 3)
plot(HJ_biplot)
