library(readr)
HR_comma_sep <- read_csv("C:/Users/danie/Desktop/HUMAN RESOURCES ANALYTICS - EQUIPO ANALISIS DE DATOS/HR_comma_sep.csv")
View(HR_comma_sep)
which(is.na(HR_comma_sep))
library(dplyr)
HR_dataset <- mutate(HR_comma_sep, project_per_year = number_project/time_spend_company)
View(HR_dataset)
summary(HR_dataset)
attach(HR_dataset)
par(mfrow=c(1,2))
hist(satisfaction_level, col = "red", xlim = c(0,1))
boxplot(satisfaction_level, col = "red", ylim= c(0,1), main = "Boxplot of Satisfaction_level")
hist(last_evaluation, col = "purple", xlim = c(0,1))
boxplot(last_evaluation, col = "purple", ylim= c(0,1), main = "Boxplot of Last_evaluation")
hist(number_project, col="green", breaks = 7)
boxplot(number_project, col="green", main = "Boxplot of number_project")
hist(average_montly_hours, col = "pink", xlim= c(50, 350))
boxplot(average_montly_hours, col = "pink", main = "Boxplot of Average_monthly_hours")
hist(time_spend_company, col = "blue", breaks = 8)
boxplot(time_spend_company, col = "blue", main = "Boxplot of time_spend_company")
hist(project_per_year, col = "orange", xlim= c(0,3))
boxplot(project_per_year, col = "orange", main = "Boxplot of project_per_year")


require(car)
HR_dataset$salarynum<-recode(HR_dataset$salary, "'low'=1")
HR_dataset$salarynum<-recode(HR_dataset$salarynum, "'medium'=2")
HR_dataset$salarynum<-recode(HR_dataset$salarynum, "'high'=3")
HR_dataset$salarynum<-as.numeric(HR_dataset$salarynum)

library(dplyr)
HR_dataset_corrplot <- select(HR_dataset, -sales, -salary)
HR_correlation <- cor(HR_dataset_corrplot)
library(corrplot)
par(mfrow=c(1,2))
corrplot(HR_correlation, method = "color", tl.cex = 0.6)
corrplot(HR_correlation, method = "number", tl.cex = 0.6)

HR_leavers <- subset(HR_dataset, HR_dataset$left == 1)
attach(HR_leavers)
par(mfrow=c(1,1))
hist(satisfaction_level, col = "blue", xlim = c(0,1))
hist(last_evaluation, col = "blue")
hist(number_project, col= "blue")
hist(average_montly_hours, col= "blue")
hist(time_spend_company, col= "blue")
hist(Work_accident, col = "blue")
library(ggplot2)
ggplot(salary)
HR_dataset$salary<-factor(HR_dataset$salary,levels=c("low","medium","high")) # Manual ordering of the levels of the variable Salary
ggplot(HR_dataset,aes(x=salary, fill=factor(left)))+
  geom_bar(stat='count',position='dodge')
library(graphics)
pairs(HR_correlation)
HR_dataset_pca <- princomp(HR_correlation)
summary(HR_dataset_pca)
plot(HR_dataset_pca)
HR_dataset_pca$loadings
library(devtools)
install_github("ggbiplot", "vqv")
library(ggbiplot)
ggbiplot(HR_dataset_pca)
